/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:e437542b-8cf1-4eb0-a5c3-5000601339fe",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_B7aR8U0yT",
    "aws_user_pools_web_client_id": "vp3hagv9n8pn1j6pfhlnh0f0m",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6hrrsyfjzzfrfo2srhku25sc3a.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
